[package]
name = "magik-macro"
version = "0.1.0"
edition = "2024"
authors = ["Daril Rodriguez <me@daril.dev>"]

[dependencies]
syn = { version = "2.0.104", features = ["full"] }
quote = "1.0.40"
magik = { path = "../magik" }
proc-macro2 = "1.0.95"

[lib]
proc-macro = true
